# 公式のComposerイメージを使用
FROM composer:latest AS composer

FROM php:8.2-fpm

#install composer
RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer

# 追加のパッケージをインストール
RUN apt-get update \
    && apt-get install -y \
        git \
        zip \
        unzip \
        vim \
        libpq-dev

# PostgreSQLのPDO拡張機能をインストール
RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo_pgsql

WORKDIR /var/www/html